// accounts
export const GET_ACCOUNT = 'GET_ACCOUNTS';

// badge contract
export const GOT_BADGE_CONTRACT = 'GOT_BADGE_CONTRACT';
export const LOADING_BADGE_CONTRACT = 'LOADING_BADGE_CONTRACT';

// network
export const GET_NETWORK = 'GET_NETWORK';

// web3
export const GET_WEB3 = 'GET_WEB3';

// get badges
export const GET_PATRONAGE_BADGES_REQUEST = 'GET_PATRONAGE_BADGES_REQUEST';
export const GET_PATRONAGE_BADGES_SUCCESS = 'GET_PATRONAGE_BADGES_SUCCESS';
export const GET_PATRONAGE_BADGES_FAILURE = 'GET_PATRONAGE_BADGES_FAILURE';

// chat
export const MESSAGE = 'MESSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const SET_ROOM = 'SET_ROOM';

// get persona
export const GET_PERSONA_REQUEST = 'GET_PERSONA_REQUEST';
export const GET_PERSONA_SUCCESS = 'GET_PERSONA_SUCCESS';
export const GET_PERSONA_FAILURE = 'GET_PERSONA_FAILURE';
